DROP TABLE IF EXISTS repertoire;
DROP TABLE IF EXISTS form;
DROP INDEX IF EXISTS idx_users_email;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS repertoire (
	unicode INTEGER PRIMARY KEY,
	tygf INTEGER,
	gb2312 INTEGER,
	pinyin TEXT
);

CREATE TABLE IF NOT EXISTS form (
	unicode INTEGER PRIMARY KEY,
	name TEXT,
	default_type INTEGER,
	gf0014_id INTEGER,
	component TEXT,
	compound TEXT,
	slice TEXT
);

CREATE TABLE IF NOT EXISTS users (
	`id` TEXT NOT NULL DEFAULT "" PRIMARY KEY,
	`name` TEXT NOT NULL DEFAULT "",
	`email` TEXT NOT NULL DEFAULT "",
	`password` TEXT NOT NULL DEFAULT "",
	`avatar` TEXT NOT NULL DEFAULT "",
	`role` INTEGER NOT NULL DEFAULT 0,
	`state` INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email);
